import { FC } from "react";
import Head from "next/head";
import { Navbar, RegisterSection } from "../../src/components/organisms";

export default function RegisterPage() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Navbar /> */}
        <RegisterSection />
        {/* <Footer /> */}
      </main>
    </div>
  );
}
