import Head from "next/head";
import { Navbar, CardsSection } from "../src/components/organisms";

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Futbol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <CardsSection />
      </main>
    </div>
  );
}
