import Head from "next/head";
import {
  Navbar,
  ProductSection,
  ProfileCard,
} from "../src/components/organisms";

export default function Profile() {
  return (
    <div>
      <Head>
        <title>E-Commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />

        <ProfileCard />

        <ProductSection />
      </main>
    </div>
  );
}
